# This is a basic workflow to help you get started with Actions

name: VaiDomleAiFlow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      numele:
        description: trebuie sa te predai, cum te cheama
        required: true
        default: Gogu din Bacaloglu

      tara-ta:
        description: de unde vii pe unde pleci
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run ww2-s1 OK
        run: echo Hellos1, world! ${{ github.event.inputs.numele }} ce cauti in cantina
      - name: ww2.Step fails
        run: exit 1
      - name: ww2.Run s23
        run: |
          echo Add s2other actions to build, ${{ github.event.inputs.tara-ta }} pt tara ta
          echo test, s3and deploy your project. ${{ github.event.inputs.numele }} pt numele tau
      - name: pompieru-pt-fail
        if: ${{ failure() }}
        run: |
         echo In ctx ${{github.repository}} s-a produs un fail la ${{ github.run_id }} trebuie chemat ${{ inputs.numele }} pt cercetari
         curl -L \
             -X POST \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer <YOUR-TOKEN>" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/repos/OWNER/REPO/issues \
             -d '{"title":"Found a bug","body":"I'\''m having a problem with this.","assignees":["octocat"],"milestone":1,"labels":["bug"]}'
